services:
  - type: web
    name: smartserve-discord-app
    env: node
    plan: starter # You can upgrade to standard or pro as needed
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true # Render will generate a secure random value
      - key: DB_HOST
        sync: false # Set this in Render dashboard to your database host
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false # Set this in Render dashboard to your database username
      - key: DB_PASSWORD
        sync: false # Set this in Render dashboard to your database password
      - key: DB_NAME
        sync: false # Set this in Render dashboard to your database name
      - key: DISCORD_CLIENT_ID
        sync: false # Set this in Render dashboard with your Discord app client ID
      - key: DISCORD_CLIENT_SECRET
        sync: false # Set this in Render dashboard with your Discord app client secret
      - key: DISCORD_BOT_TOKEN
        sync: false # Set this in Render dashboard with your main Discord bot token
      - key: BOT2_TOKEN
        sync: false # Set this in Render dashboard with your quest bot token (if using a second bot)
      - key: STRIPE_SECRET_KEY
        sync: false # Set this in Render dashboard with your Stripe secret key
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false # Set this in Render dashboard with your Stripe publishable key
      - key: APP_URL
        sync: false # Set this to your Render app URL (e.g., https://your-app-name.onrender.com)
    autoDeploy: true # Enable auto-deploy from your main branch
    
# Optional: If you want to use Render's PostgreSQL database instead of external MySQL
# databases:
#   - name: smartserve-db
#     plan: starter # You can upgrade as needed
#     databaseName: smartserve
#     user: smartserve_user

# If using Render's database, uncomment above and set these environment variables instead:
# - key: DATABASE_URL
#   fromDatabase:
#     name: smartserve-db
#     property: connectionString